# Generated by Django 5.2 on 2025-05-23
from django.db import migrations, models
from phonenumber_field.modelfields import PhoneNumberField
import random
import string

def generate_passcodes(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    for profile in Profile.objects.all():
        if not profile.student_passcode:  # Only generate if passcode is unset
            while True:
                passcode = ''.join(random.choices(string.digits, k=4))
                if not Profile.objects.filter(student_passcode=passcode).exists():
                    profile.student_passcode = passcode
                    profile.save()
                    break

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cohort_facebook_link_cohort_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Profile',
            name='mobile_number',
            field=PhoneNumberField(blank=True, null=True, help_text='Include country code, e.g., +2341234567890'),
        ),
        migrations.AddField(
            model_name='Profile',
            name='student_passcode',
            field=models.CharField(max_length=4, unique=True, blank=True, null=True, help_text='Unique 4-digit passcode'),
        ),
        migrations.RunPython(generate_passcodes, reverse_code=migrations.RunPython.noop),
    ]