# Generated by Django 5.2 on 2025-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='is_open_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
