# Generated by Django 5.2 on 2026-07-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livesession_is_open_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_plus', '45+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='how_heard',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('friend', 'Friend/Referral'), ('search', 'Search Engine'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='joined_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='joined_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='joined_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='joined_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquizresponse',
            name='programming_experience',
            field=models.CharField(blank=True, choices=[('none', 'No experience'), ('beginner', 'Beginner (less than 1 year)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3+ years)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='core.course'),
        ),
        migrations.AlterField(
            model_name='onboardingquizresponse',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onboardingquizresponse',
            name='has_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingquizresponse',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
