# Generated by Django 5.2 on 2026-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_onboardingquizresponse_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
