from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('create_course/', views.create_course, name='create_course'),
    path('courses/', views.course_list, name='course_list'),
    path('course_enrollment/', views.course_enrollment, name='course_enrollment'),
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
    path('courses/<int:course_id>/enroll/', views.enroll_course, name='enroll_course'),
    path('upload_payment_slip/<int:course_id>/', views.upload_payment_slip, name='upload_payment_slip'),
    path('register/', views.register, name='register'),
    path('change_course/', views.change_course, name='change_course'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.student_dashboard, name='student_dashboard'),
    path('facilitator_dashboard/', views.facilitator_application_dashboard, name='facilitator_dashboard'),
    path('admin_dashboard/', views.admin_dashboard, name='admindashboard'),
    path('manage_facilitators/', views.manage_facilitators, name='manage_facilitators'),
    path('manage_cohorts/', views.manage_cohorts, name='manage_cohorts'),
    path('schedule_session/', views.schedule_session, name='schedule_session'),
    path('live_session/', views.live_session, name='live_session'),
    path('recap_session/', views.recap_session, name='recap_session'),
    path('inbox/', views.inbox, name='inbox'),
    path('course_library/', views.course_library, name='course_library'),
    path('edit_portfolio/', views.edit_portfolio, name='edit_portfolio'),
    path('portfolio/<str:username>/', views.portfolio_view, name='portfolio_view'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('onboarding_quiz/', views.onboarding_quiz, name='onboarding_quiz'),
    path('facilitator_application/', views.facilitator_application, name='facilitator_application'),
    path('payment_approval/', views.payment_approval, name='payment_approval'),
    path('approve_payment/<int:slip_id>/', views.approve_payment, name='approve_payment'),
    path('submit_salary/', views.submit_salary, name='submit_salary'),
    path('salary_approval/', views.salary_approval, name='salary_approval'),
    path('approve_salary/<int:submission_id>/', views.approve_salary, name='approve_salary'),
    path('two_factor_setup/', views.two_factor_setup, name='two_factor_setup'),
    path('verify_admin_access/', views.verify_admin_access, name='verify_admin_access'),
    path('feature_portfolio/<int:portfolio_id>/', views.feature_portfolio, name='feature_portfolio'),
    path('toggle_notifications/', views.toggle_notifications, name='toggle_notifications'),
    path('grade_submission/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('manage_performance/<int:record_id>/', views.manage_performance, name='manage_performance'),
    path('log_material_access/<int:material_id>/', views.log_material_access, name='log_material_access'),
    path('submit_assignment/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('submit_project/<int:project_id>/', views.submit_project, name='submit_project'),
    path('discussion_board/<int:cohort_id>/', views.discussion_board, name='discussion_board'),
    path('create_discussion_post/<int:cohort_id>/', views.create_discussion_post, name='create_discussion_post'),
    path('add_discussion_comment/<int:post_id>/', views.add_discussion_comment, name='add_discussion_comment'),
    path('assign_student_leader/<int:cohort_id>/', views.assign_student_leader, name='assign_student_leader'),
    path('get_notifications/', views.get_notifications, name='get_notifications'),
    path('apply_for_course/', views.apply_for_course, name='apply_for_course'),
    path('create_profile/', views.create_profile, name='create_profile'),  # Added
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'), name='password_reset_complete'),
]


